/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.h4h.terminology

import io.h4h.terminology.codesets.AppleWatchEKGClassification
import io.h4h.terminology.codesets.MDC
import kotlin.test.Test


class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        println(MDC.values())
        println(AppleWatchEKGClassification.values())
        println(AppleWatchEKGClassification.sinusRhythm.coding)
    }
}
